using Azure;
using Azure.Storage.Blobs;
using Azure.Storage.Blobs.Models;
using BookExchange.Application.Abstractions;
using Microsoft.Extensions.Options;

namespace BookExchange.Infrastructure.Storage;

public sealed class StorageOptions
{
    public const string SectionName = "Storage";

    /// <summary>"Blob" (Azure Blob / Azurite) or "LocalDisk".</summary>
    public string Provider { get; set; } = "LocalDisk";

    public string LocalRootPath { get; set; } = ".data/uploads";

    public string? BlobConnectionString { get; set; }

    public string BlobContainer { get; set; } = "listing-images";
}

/// <summary>Azure Blob Storage (Azurite in development). The container is private; files are served by the API.</summary>
internal sealed class BlobFileStorage(IOptions<StorageOptions> options) : IFileStorage, IDisposable
{
    private readonly BlobContainerClient _container = new(options.Value.BlobConnectionString, options.Value.BlobContainer);
    private readonly SemaphoreSlim _gate = new(1, 1);
    private volatile bool _containerReady;

    public void Dispose() => _gate.Dispose();

    public async Task SaveAsync(string key, Stream content, string contentType, CancellationToken cancellationToken)
    {
        await EnsureContainerAsync(cancellationToken);
        await _container.GetBlobClient(key).UploadAsync(
            content,
            new BlobUploadOptions { HttpHeaders = new BlobHttpHeaders { ContentType = contentType } },
            cancellationToken);
    }

    public async Task<StoredFile?> OpenReadAsync(string key, CancellationToken cancellationToken)
    {
        await EnsureContainerAsync(cancellationToken);
        try
        {
            var result = await _container.GetBlobClient(key).DownloadStreamingAsync(cancellationToken: cancellationToken);
            return new StoredFile(result.Value.Content, result.Value.Details.ContentType);
        }
        catch (RequestFailedException e) when (e.Status == 404)
        {
            return null;
        }
    }

    public async Task DeleteAsync(string key, CancellationToken cancellationToken)
    {
        await EnsureContainerAsync(cancellationToken);
        await _container.GetBlobClient(key).DeleteIfExistsAsync(cancellationToken: cancellationToken);
    }

    /// <summary>
    /// Creates the container once. A failure is not remembered (unlike a cached Lazy task), so a blip at
    /// startup doesn't break every later upload.
    /// </summary>
    private async Task EnsureContainerAsync(CancellationToken cancellationToken)
    {
        if (_containerReady)
        {
            return;
        }

        await _gate.WaitAsync(cancellationToken);
        try
        {
            if (!_containerReady)
            {
                await _container.CreateIfNotExistsAsync(PublicAccessType.None, cancellationToken: cancellationToken);
                _containerReady = true;
            }
        }
        finally
        {
            _gate.Release();
        }
    }
}

/// <summary>Files under a root folder (tests, and running the API outside Docker).</summary>
internal sealed class LocalDiskFileStorage(IOptions<StorageOptions> options) : IFileStorage
{
    private readonly string _root = Path.GetFullPath(options.Value.LocalRootPath);

    public async Task SaveAsync(string key, Stream content, string contentType, CancellationToken cancellationToken)
    {
        var path = PathFor(key);
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        await using var file = File.Create(path);
        await content.CopyToAsync(file, cancellationToken);
    }

    public Task<StoredFile?> OpenReadAsync(string key, CancellationToken cancellationToken)
    {
        var path = PathFor(key);
        return Task.FromResult(File.Exists(path)
            ? new StoredFile(File.OpenRead(path), ContentTypeFor(path))
            : null);
    }

    public Task DeleteAsync(string key, CancellationToken cancellationToken)
    {
        File.Delete(PathFor(key));
        return Task.CompletedTask;
    }

    /// <summary>Keys are generated by the app, but never let one escape the root folder.</summary>
    private string PathFor(string key)
    {
        var path = Path.GetFullPath(Path.Combine(_root, key));
        return path.StartsWith(_root + Path.DirectorySeparatorChar, StringComparison.Ordinal)
            ? path
            : throw new ArgumentException("Invalid storage key.", nameof(key));
    }

    private static string ContentTypeFor(string path) => Path.GetExtension(path).ToLowerInvariant() switch
    {
        ".webp" => "image/webp",
        ".jpg" or ".jpeg" => "image/jpeg",
        ".png" => "image/png",
        _ => "application/octet-stream",
    };
}
