<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\BookExchange.Domain\BookExchange.Domain.csproj" />
    <ProjectReference Include="..\..\src\BookExchange.Application\BookExchange.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
</Project>
